Repository keymanapp/api.keyman.com, pull requests merged in 2020-06, with the labels that each got.

#53 feat: test case infrastructure - consistent mockable data sources
  .github/workflows/ci.yml
  README.md
  configure.ps1
  script/hooks/keyboards-build-success.php
  tests/SearchTest.php
  tests/TestDBBuild.inc.php
  tests/data/CountryCodes.tab
  tests/data/LanguageCodes.tab
  tests/data/LanguageIndex.tab
  tests/data/README.md
  tests/data/iso-639-3.tab
  tests/data/iso-639-3_Name_Index.tab
  tests/data/keyboard_info.zip
  tests/data/langtags.json
  tests/data/language-subtag-registry
  tests/data/model_info.zip
  tools/db/build/build.inc.php
  tools/db/build/build_cli.php
  tools/db/build/build_keyboards_script.inc.php
  tools/db/build/build_langtags_data_script.inc.php
  tools/db/build/build_models_script.inc.php
  tools/db/build/build_standards_data_script.inc.php
  tools/db/build/cjk/build.inc.php
  tools/db/build/cjk/build_cjk_data_script.inc.php
  tools/db/build/cjk/build_cli.php
  tools/db/build/common.inc.php
  tools/db/build/datasources.inc.php
  tools/db/build/search.sql
  tools/db/servervars.php
Labels: enhancement

#56 test: model endpoint schema validation
  schemas/model_info.distribution/1.0/model_info.distribution.json
  script/model/model.inc.php
  script/model/model.php
  tests/ModelTest.php
Labels: enhancement

#54 feat: clean up globals and namespaces, include stub test classes
  .github/workflows/ci.yml
  script/keyboard/keyboard.php
  script/legacy/legacy_db.php
  script/model/model.php
  script/model/model_search.php
  script/search/search.inc.php
  script/search/search.php
  tests/ChinesePinyinTest.php
  tests/JapaneseTest.php
  tests/KeyboardTest.php
  tests/Legacy10.php
  tests/ModelSearchTest.php
  tests/ModelTest.php
  tests/PackageVersionTest.php
  tests/SearchTest.php
  tests/TestDBBuild.inc.php
  tests/TestUtils.inc.php
  tests/VersionTest.php
  tests/data/keyboard_info.zip
  tests/data/model_info.zip
  tests/fixtures/Search.khmer.json
  tools/db/build/build.inc.php
  tools/db/build/build_cli.php
  tools/db/build/datasources.inc.php
  tools/db/build/search-queries.sql
  tools/db/build/search.sql
  tools/db/db.php
  tools/db/servervars.php
  tools/util.php
Labels: enhancement

#55 test: package-version basic test case
  .github/workflows/ci.yml
  configure.ps1
  schemas/model-search/1.0/model-search.json
  schemas/model_info.distribution/1.0/model_info.distribution.json
  schemas/web.config
  script/model-search/model-search.inc.php
  script/model-search/model-search.php
  script/model/model.inc.php
  script/model/model.php
  script/model/model_search.php
  script/package-version/package-version.inc.php
  script/package-version/package-version.php
  tests/ModelSearchTest.php
  tests/ModelTest.php
  tests/PackageVersionTest.php
  web.config
Labels: enhancement

#59 feat: initial test case for /keyboard
  schemas/keyboard_info.source/1.0.6/keyboard_info.source.json
  script/keyboard/keyboard.inc.php
  script/keyboard/keyboard.php
  tests/KeyboardTest.php
Labels: feat

#60 feat: version schema initial test case
  script/version/version.inc.php
  script/version/version.php
  tests/VersionTest.php
Labels: feat

#62 change: package schema now draft-04 compliant
  schemas/package/1.1.0/package.json
Labels: api.keyman.com, enhancement

#61 feat: start to run tests against web endpoint
  .github/workflows/ci.yml
  composer.json
  phpunit.xml
  tests/Legacy10Test.php
  tests/TestUtils.inc.php
  tests/rest/RestVersionTest.php
  web.config
Labels: feat, staging

#63 feat: groundwork for rest-based test cases
  composer.json
  composer.lock
  tests/rest/RestTestCase.php
  tests/rest/RestVersionTest.php
  tools/util.php
Labels: feat

#64 feat: add more cloud tests
  .github/workflows/ci.yml
  composer.json
  schemas/keymanweb-cloud-api/keymanweb-cloud-api-1.0.json
  schemas/keymanweb-cloud-api/keymanweb-cloud-api-2.0.json
  schemas/keymanweb-cloud-api/keymanweb-cloud-api-3.0.json
  schemas/keymanweb-cloud-api/keymanweb-cloud-api-4.0.json
  script/legacy/legacy40.php
  script/legacy/legacy_db.php
  tests/Legacy10Test.php
  tests/TestDBBuild.inc.php
  tests/data/keyboard_info.zip
  tests/fixtures/cloud/1.0-keyboard-chinese.json
  tests/fixtures/cloud/1.0-language-th.json
  tests/fixtures/cloud/2.0-keyboard-canadian_ms-fr.json
  tests/fixtures/cloud/2.0-keyboard-tamil.json
  tests/fixtures/cloud/2.0-language-ta.json
  tests/fixtures/cloud/3.0-keyboard-european-en.json
  tests/fixtures/cloud/3.0-keyboard-us.json
  tests/fixtures/cloud/3.0-language-en-european.json
  tests/fixtures/cloud/3.0-language-khm.json
  tests/fixtures/cloud/4.0-keyboard-gff_tir_et_7-ti.json
  tests/fixtures/cloud/4.0-keyboard-sil_uganda_tanzania.json
  tests/fixtures/cloud/4.0-language-am.json
  tests/fixtures/cloud/4.0-language-ti-gff_tir_et_7.json
  tests/fixtures/cloud/_invalid_2.0-keyboard-ta.json
  tests/rest/RestCloudTest.php
  tools/db/build/build.inc.php
  tools/db/build/common.inc.php
  tools/db/build/legacy-queries.sql
  tools/db/db.php
  web.config
Labels: feat

#65 feat: CJK tests
  script/cjk/chinese_pinyin.php
  script/cjk/japanese.php
  tests/ChinesePinyinTest.php
  tests/JapaneseTest.php
  tests/fixtures/chinese_pinyin-bei.js
  tests/fixtures/chinese_pinyin-ta.js
  tests/fixtures/japanese-love.js
  tests/rest/RestChinesePinyinTest.php
  tests/rest/RestJapaneseTest.php
  tests/rest/RestTestCase.php
  tests/rest/RestVersionTest.php
  tools/db/build/legacy-queries.sql
Labels: feat

#69 fix: keyboard id search
  script/search/2.0/search.inc.php
  tests/Search20Test.php
  tests/fixtures/Search.2.0.khmer.json
  tools/db/build/sp_keyboard_search.sql
Labels: fix

#68 fix: phrase and Unicode searches
  script/search/2.0/search.inc.php
  tests/Search20Test.php
  tests/fixtures/Search.2.0.ethiopic.json
  tests/fixtures/Search.2.0.khmer-angkor.json
  tests/fixtures/Search.2.0.khmer.json
  tools/db/build/sp_keyboard_search.sql
Labels: fix

#77 feat: add bcp47 tag for language results
  schemas/search/2.0/search.json
  script/search/2.0/search.inc.php
  tests/fixtures/Search.2.0.ethiopic.json
  tests/fixtures/Search.2.0.khmer.json
  tools/db/build/sp_keyboard_search.sql
  tools/db/build/sp_keyboard_search_by_id.sql
  tools/db/build/sp_keyboard_search_by_language_bcp47_tag.sql
  tools/db/build/sp_keyboard_search_by_legacy_id.sql
Labels: feat

#76 fix: schema value types for match fields
  schemas/keyboard_info.source/1.0.6/keyboard_info.source.json
  schemas/search/2.0/search.json
  script/search/2.0/search.inc.php
  tests/fixtures/Search.2.0.ethiopic.json
  tests/fixtures/Search.2.0.khmer-angkor.json
  tests/fixtures/Search.2.0.khmer-keyboards.json
  tests/fixtures/Search.2.0.khmer.json
  tools/db/build/sp_keyboard_search.sql
  tools/db/build/sp_keyboard_search_by_id.sql
  tools/db/build/sp_keyboard_search_by_language_bcp47_tag.sql
  tools/db/build/sp_keyboard_search_by_legacy_id.sql
Labels: fix

#75 fix: adjust langtag search weight
  schemas/keyboard_info.source/1.0.6/keyboard_info.source.json
  schemas/search/2.0/search.json
  script/search/2.0/search.inc.php
  tests/fixtures/Search.2.0.ethiopic.json
  tests/fixtures/Search.2.0.khmer-angkor.json
  tests/fixtures/Search.2.0.khmer-keyboards.json
  tests/fixtures/Search.2.0.khmer.json
  tools/db/build/sp_keyboard_search.sql
  tools/db/build/sp_keyboard_search_by_id.sql
  tools/db/build/sp_keyboard_search_by_language_bcp47_tag.sql
  tools/db/build/sp_keyboard_search_by_legacy_id.sql
Labels: fix

#74 refactor: region vs country in search
  schemas/keyboard_info.source/1.0.6/keyboard_info.source.json
  schemas/search/2.0/search.json
  script/search/2.0/search.inc.php
  tests/fixtures/Search.2.0.ethiopic.json
  tests/fixtures/Search.2.0.khmer-angkor.json
  tests/fixtures/Search.2.0.khmer-keyboards.json
  tests/fixtures/Search.2.0.khmer.json
  tools/db/build/sp_keyboard_search.sql
  tools/db/build/sp_keyboard_search_by_country.sql
  tools/db/build/sp_keyboard_search_by_country_iso3166_code.sql
  tools/db/build/sp_keyboard_search_by_id.sql
  tools/db/build/sp_keyboard_search_by_language.sql
  tools/db/build/sp_keyboard_search_by_language_bcp47_tag.sql
  tools/db/build/sp_keyboard_search_by_legacy_id.sql
  tools/db/build/sp_keyboard_search_by_script_iso15924_code.sql
Labels: fix

#73 refactor: id code tag slightly more consistent
  schemas/keyboard_info.source/1.0.6/keyboard_info.source.json
  schemas/search/2.0/search.json
  script/search/2.0/search.inc.php
  script/search/2.0/search.php
  tests/Search20Test.php
  tests/fixtures/Search.2.0.ethiopic.json
  tests/fixtures/Search.2.0.khmer-angkor.json
  tests/fixtures/Search.2.0.khmer-keyboards.json
  tests/fixtures/Search.2.0.khmer.json
  tools/db/build/search-langtags.sql
  tools/db/build/sp_keyboard_search.sql
  tools/db/build/sp_keyboard_search_by_country.sql
  tools/db/build/sp_keyboard_search_by_country_iso3166_code.sql
  tools/db/build/sp_keyboard_search_by_id.sql
  tools/db/build/sp_keyboard_search_by_keyboard.sql
  tools/db/build/sp_keyboard_search_by_language.sql
  tools/db/build/sp_keyboard_search_by_language_bcp47_tag.sql
  tools/db/build/sp_keyboard_search_by_legacy_id.sql
  tools/db/build/sp_keyboard_search_by_script_iso15924_code.sql
Labels: fix

#72 feat: search pagination enabled
  schemas/keyboard_info.source/1.0.6/keyboard_info.source.json
  schemas/search/2.0/search.json
  script/search/2.0/search.inc.php
  script/search/2.0/search.php
  tests/Search20Test.php
  tests/fixtures/Search.2.0.ethiopic.json
  tests/fixtures/Search.2.0.khmer-angkor.json
  tests/fixtures/Search.2.0.khmer-keyboards.json
  tests/fixtures/Search.2.0.khmer.json
  tools/db/build/search-langtags.sql
  tools/db/build/sp_keyboard_search.sql
  tools/db/build/sp_keyboard_search_by_country.sql
  tools/db/build/sp_keyboard_search_by_country_iso3166_code.sql
  tools/db/build/sp_keyboard_search_by_id.sql
  tools/db/build/sp_keyboard_search_by_keyboard.sql
  tools/db/build/sp_keyboard_search_by_language.sql
  tools/db/build/sp_keyboard_search_by_language_bcp47_tag.sql
  tools/db/build/sp_keyboard_search_by_legacy_id.sql
  tools/db/build/sp_keyboard_search_by_script_iso15924_code.sql
Labels: feat

#82 feat: search by popularity
  script/search/2.0/search.inc.php
  tests/Search20Test.php
  tools/db/build/sp_keyboard_search.sql
  tools/db/build/sp_keyboard_search_by_popularity.sql
Labels: feat

#81 fix: clean string was too aggressive
  script/search/2.0/search.inc.php
  tests/Search20Test.php
  tools/db/build/sp_keyboard_search.sql
  tools/db/build/sp_keyboard_search_by_popularity.sql
Labels: fix

#79 feat: support custom language names and tags
  schemas/keyboard_info.source/1.0.6/keyboard_info.source.json
  script/search/2.0/search.inc.php
  tests/Search20Test.php
  tools/db/LangTags.php
  tools/db/build/build_keyboards_script.inc.php
  tools/db/build/langtags.sql
  tools/db/build/search-prepare-data.sql
  tools/db/build/sp_keyboard_search.sql
  tools/db/build/sp_keyboard_search_by_popularity.sql
Labels: feat

#78 fix: some searches failed with truncation
  schemas/keyboard_info.source/1.0.6/keyboard_info.source.json
  script/search/2.0/search.inc.php
  tests/Search20Test.php
  tools/db/LangTags.php
  tools/db/build/build_keyboards_script.inc.php
  tools/db/build/langtags.sql
  tools/db/build/search-prepare-data.sql
  tools/db/build/sp_country_search_10.sql
  tools/db/build/sp_keyboard_search.sql
  tools/db/build/sp_keyboard_search_by_popularity.sql
  tools/db/build/sp_language_search_10.sql
Labels: fix
