Repository keymanapp/api.keyman.com, pull requests merged in 2020-07, with the labels that each got.

#83 feat: support updates for windows 14.0
  schemas/windows-update/14.0/windows-update.json
  script/model-search/model-search.inc.php
  script/model/model.inc.php
  script/package-version/package-version.inc.php
  script/package-version/package-version.php
  script/windows/14.0/update/WindowsUpdateCheck.php
  script/windows/14.0/update/index.php
  tests/ApiTestCase.php
  tests/VersionTest.php
  tests/WindowsUpdateCheckTest.php
  tests/fixtures/WindowsUpdateCheck.14.0.json
  tests/fixtures/downloads.keyman.com/keyboard/khmer_angkor.json
  tests/fixtures/downloads.keyman.com/version.json
  tests/fixtures/downloads.keyman.com/version/windows.json
  tests/fixtures/downloads.keyman.com/version/windows/2.0.json
  tests/rest/RestTestCase.php
  tools/2020/DownloadsApi.php
  tools/2020/KeymanHosts.php
  tools/autoload.php
  tools/keymanversion.php
  tools/onlineupdate.php
  tools/util.php
  web.config
Labels: feat

#85 chore: prune unused code
  script/windows/14.0/update/WindowsUpdateCheck.php
  script/windows/14.0/update/index.php
  tests/WindowsUpdateCheckTest.php
  tests/fixtures/WindowsUpdateCheck.14.0.json
Labels: chore

#86 chore: merge master into staging (P10S10 changes)
  schemas/package/1.1.0/package.json
Labels: chore

#88 fix: ethnologue data is now static
  static-data/ethnologue_country_codes.tab
  static-data/ethnologue_language_codes.tab
  static-data/ethnologue_language_index.tab
  tests/data/ethnologue_country_codes.tab
  tests/data/ethnologue_language_codes.tab
  tests/data/ethnologue_language_index.tab
  tools/db/build/datasources.inc.php
Labels: fix

#90 chore: update host names
  composer.json
  script/keyboard/keyboard.php
  script/legacy/legacy10.php
  script/legacy/legacy20.php
  script/legacy/legacy30.php
  script/legacy/legacy40.php
  script/model-search/model-search.php
  script/model/model.php
  script/package-version/package-version.inc.php
  script/package-version/package-version.php
  script/search/1.0/search.php
  script/search/2.0/search.php
  script/version/version.php
  tests/fixtures/WindowsUpdateCheck.14.0.json
  tests/rest/RestCloudTest.php
  tests/rest/RestTestCase.php
  tools/2020/KeymanHosts.php
  web.config
Labels: chore

#89 docs: Update readme
  README.md
Labels: staging

#91 fix: typo in web.config
  web.config
Labels: fix

#93 chore: move KeymanHosts.php to common
  _common/KeymanHosts.php
  script/keyboard/keyboard.php
  script/legacy/legacy10.php
  script/legacy/legacy20.php
  script/legacy/legacy30.php
  script/legacy/legacy40.php
  script/model-search/model-search.inc.php
  script/model-search/model-search.php
  script/model/model.inc.php
  script/model/model.php
  script/package-version/package-version.inc.php
  script/package-version/package-version.php
  script/search/1.0/search.php
  script/search/2.0/search.php
  script/version/version.php
  script/windows/14.0/update/WindowsUpdateCheck.php
  tests/ApiTestCase.php
  tests/CommonFilesTest.php
  tests/rest/RestTestCase.php
  tools/2020/DownloadsApi.php
  tools/autoload.php
  tools/keymanversion.php
  tools/onlineupdate.php
Labels: chore

#92 chore: common files
  _common/KeymanHosts.php
  _common/KeymanSentry.php
  _common/README.md
  script/keyboard/keyboard.php
  script/legacy/legacy10.php
  script/legacy/legacy20.php
  script/legacy/legacy30.php
  script/legacy/legacy40.php
  script/model-search/model-search.inc.php
  script/model-search/model-search.php
  script/model/model.inc.php
  script/model/model.php
  script/package-version/package-version.inc.php
  script/package-version/package-version.php
  script/search/1.0/search.php
  script/search/2.0/search.php
  script/version/version.php
  script/windows/14.0/update/WindowsUpdateCheck.php
  tests/ApiTestCase.php
  tests/CommonFilesTest.php
  tests/rest/RestTestCase.php
  tools/2020/DownloadsApi.php
  tools/autoload.php
  tools/base.inc.php
  tools/keymanversion.php
  tools/onlineupdate.php
Labels: chore

#94 chore: add common/jsonapifailure
  _common/JsonApiFailure.php
Labels: chore

#95 refactor: remove locale download api for Keyman for Windows 14+
  web.config
Labels: refactor
