Repository keymanapp/api.keyman.com, pull requests merged in 2023-11, with the labels that each got.

#215 fix: error when submitting diagnostic report
  script/desktop/10.0/submitdiag/index.php
Labels: fix

#216 chore: _control/info
  _control/info.php
Labels: staging, chore

#217 fix: Pin sha of server:2022-latest 🦭
  mssql.Dockerfile
Labels: staging

#218 fix: Pin sha of php:7.4-apache 🦭
  Dockerfile
Labels: staging
