Repository keymanapp/api.keyman.com, pull requests merged in 2023-07, with the labels that each got.

#198 fix: sum search weights when multiple instances of same term
  tools/db/build/sp_keyboard_search.sql
Labels: fix

#199 chore: Update URLs
  tools/db/build/datasources.inc.php
Labels: chore

#202 fix: use alternate select to improve search weights
  tools/db/build/sp_keyboard_search.sql
Labels: fix

#200 chore: Merge master into staging (A17S16)
  tools/db/build/datasources.inc.php
  tools/db/build/sp_keyboard_search.sql
Labels: staging
