Repository keymanapp/api.keyman.com, pull requests merged in 2023-10, with the labels that each got.

#208 feat: use shared sites infrastructure
  .gitignore
  _common/JsonApiFailure.php
  _common/KeymanHosts.php
  _common/KeymanSentry.php
  _common/MarkdownHost.php
  _common/README.md
  build.sh
  resources/builder.inc.sh
  script/version/version.php
  tests/ApiTestCase.php
  tests/CommonFilesTest.php
  tools/db/servervars.php
Labels: feat

#209 chore: Add init-container.sh 🦭
  .gitattributes
  Dockerfile
  build.sh
  resources/init-container.sh
Labels: staging

#204 chore: remove deprecated field data from keyboard_info usage 🎺
  resources/init-container.sh
  schemas/.htaccess
  schemas/README.md
  schemas/keyboard_info/2.0/keyboard_info.schema.json
  schemas/search/3.0/search.json
  schemas/windows-update/17.0/windows-update.json
  tests/Search20Test.php
  tools/db/build/build_keyboards_script.inc.php
  tools/db/localenv.php.in
Labels: chore, epic-package-metadata

#210 chore: reorganize and update schemas
  schemas/.htaccess
  schemas/README.md
  schemas/developer-update/README.md
  schemas/displaymap/1.0/displaymap.schema.json
  schemas/displaymap/README.md
  schemas/keyboard_info/README.md
  schemas/keyboard_json/README.md
  schemas/keyman-touch-layout/2.1/keyman-touch-layout.clean.spec.json
  schemas/keyman-touch-layout/2.1/keyman-touch-layout.spec.json
  schemas/keyman-touch-layout/README.md
  schemas/keymanweb-cloud-api/README.md
  schemas/kmp/1.0.1/kmp.schema.json
  schemas/kmp/1.0.2/kmp.schema.json
  schemas/kmp/1.0/kmp.schema.json
  schemas/kmp/1.1.0/kmp.schema.json
  schemas/kmp/README.md
  schemas/kpj-9.0/README.md
  schemas/kpj-9.0/kpj-9.0.schema.json
  schemas/kpj/README.md
  schemas/kpj/kpj.schema.json
  schemas/kps/17.0/kps.xsd
  schemas/kps/README.md
  schemas/kvk/kvk.ksy
  schemas/kvks/README.md
  schemas/kvks/kvks.schema.json
  schemas/kvks/kvks.xsd
  schemas/model_info.distribution/README.md
  schemas/model_info.source/README.md
  schemas/package-version/README.md
  schemas/search/README.md
  schemas/version/README.md
  schemas/visualkeyboard/README.md
  schemas/windows-update/README.md
Labels: chore

#211 chore: add kmp.schema.json v2.0
  schemas/kmp/2.0/kmp.schema.json
  schemas/kmp/README.md
Labels: chore
