Repository keymanapp/api.keyman.com, pull requests merged in 2023-02, with the labels that each got.

#176 fix: handle langtags reserved _tags
  tools/db/build/build_langtags_data_script.inc.php
Labels: fix

#177 chore: cleanup langtags processor
  tools/db/build/build_langtags_data_script.inc.php
Labels: chore

#179 chore: Merge master end of Sprint A17S6 to staging
  tools/db/build/build_langtags_data_script.inc.php
Labels: staging

#181 chore: remove google-client dependency, unused
  composer.json
  composer.lock
Labels: chore

#182 chore: remove packagist repo from composer.json
  composer.json
Labels: chore

#180 chore: Migrate site to Apache with Docker
  .gitignore
  .htaccess
  Dockerfile
  build.sh
  composer.json
  mssql.Dockerfile
  resources/builder.inc.sh
  resources/keyman-site.conf
  tools/autoload.php
Labels: feat
