Repository keymanapp/api.keyman.com, pull requests merged in 2024-02, with the labels that each got.

#225 Update staging to use shared-sites v0.4
  build.sh
Labels: staging

#226 Update production to use shared-sites v0.4 :cherries:
  build.sh
Labels: production

#228 chore: Remove unused comments in .htaccess
  .htaccess
Labels: staging

#229 chore: disable php-based webhook in .htaccess
  .htaccess
Labels: chore

#233 chore: cleanup schema paths and docs
  schemas/keyboard_info/README.md
  schemas/kvk/1.0/kvk.ksy
  schemas/kvk/README.md
  schemas/kvks/10.0/kvks.schema.json
  schemas/kvks/10.0/kvks.xsd
  schemas/kvks/README.md
  schemas/search/README.md
  schemas/windows-update/README.md
Labels: staging, chore

#232 chore: Add liveliness check
  _control/alive
Labels: staging, chore

#234 fix: move activeschema.txt into shared .data/
  _control/ready.php
  tools/db/.gitignore
  tools/db/servervars.php
Labels: fix

#237 fix: no schema prefix for production
  tools/db/servervars.php
Labels: fix

#236 fix: no schema prefix for production
  tools/db/servervars.php
Labels: staging, fix

#238 chore: Add info to .htaccess
  .htaccess
  _control/info.php
Labels: production

#241 fix: force re-download of data when building database
  Dockerfile
  composer.json
  resources/init-container.sh
  tests/data/README.md
Labels: fix

#243 chore(common): loosen .keyman-touch-layout schema layer id requirements
  schemas/keyman-touch-layout/2.1.1/keyman-touch-layout.clean.spec.json
  schemas/keyman-touch-layout/2.1.1/keyman-touch-layout.spec.json
  schemas/keyman-touch-layout/README.md
Labels: chore
