Repository keymanapp/api.keyman.com, pull requests merged in 2025-05, with the labels that each got.

#279 maint: v0.22
  build.sh
Labels: maint

#280 chore: Merge master to staging for Sprint A19S2
  build.sh
Labels: staging

#287 auto: update shared-sites version to v1.0.2
  build.sh
Labels: auto
