Repository keymanapp/api.keyman.com, pull requests merged in 2025-01, with the labels that each got.

#266 chore: disable database readiness check
  _control/ready.php
Labels: chore

#269 chore: merge master to staging for Sprint A18S20
  .github/workflows/add-to-keyman-project.yml
  .gitignore
  .htaccess
  .user.ini
  _control/ready.php
  applicationHost.xdt
  build.sh
  configure.ps1
  schemas/keyman-touch-layout/2.1.1/keyman-touch-layout.clean.spec.json
  schemas/keyman-touch-layout/2.1.1/keyman-touch-layout.spec.json
  schemas/keyman-touch-layout/README.md
  script/desktop/10.0/exception/index.php
  script/desktop/10.0/submitdiag/index.php
  script/legacy/legacy40.php
  script/search/2.0/search.inc.php
  script/statistics/annual-statistics.inc.php
  script/statistics/annual.php
  tools/db/build/annual-statistics.sql
  tools/db/build/build.inc.php
  tools/db/build/build_keyboards_script.inc.php
  tools/db/build/search-prepare-data-1.sql
  tools/db/build/search-prepare-data-2.sql
  tools/db/build/search-prepare-data-3.sql
  tools/db/build/search-prepare-data-4.sql
  tools/db/build/search-prepare-data-5.sql
  tools/db/build/search-prepare-data-6.sql
  tools/db/build/search-prepare-data-7.sql
  tools/db/build/search-prepare-data-8.sql
  tools/db/build/search-prepare-data-9.sql
  tools/db/build/search-prepare-data.sql
  tools/db/build/search.sql
Labels: staging, chore

#267 fix: Update mssql.Dockerfile server:2022-latest to newer pin
  mssql.Dockerfile
Labels: staging
